### ISSUE TITLE
Mistaken reading of go benchmark tool

### ISSUE THREAD

**Issue by belak** [codygman/faster-command-line-tools-with-haskell#1]
As @burntsushi commented [here](https://www.reddit.com/r/programming/comments/6qmhuy/faster_command_line_tools_with_haskell/dkym7vl/) the Haskell version isn't actually faster.

You can see by the benchmark output that each iteration is running in about 20000000 ns, or 0.25 s. Also, the total time reported by the benchmark tool (the 2 s you were seeing) seems to include compilation time.

There are also a few interesting optimizations mentioned there, relating to memory mapping the files which could provide additional improvements for both languages.

I'm not really sure where the best place is to comment on this, as your blog doesn't have comments, so I figured this would be close enough.

**Comment by belak** [comment]
Closing this because there's an actual repo for the blog that I missed.

**Comment by codygman** [comment]
@belak Sorry, my blog situation with 2 repos is bit strange so I don't blame you for not seeing it.

Apologies for my confusion. I am considering making a part two or "(revised)" version that is more carefully and goes deeper into matching performance and analyzing why exactly the compiler was not sufficiently smart enough to match human profiling.

Any thoughts on that? Hopefully I've not damaged my credibility too much with my benchmark mistake :S

**Comment by belak** [comment]
I don't think it's a huge issue. It's pretty easy to make mistakes when you're dealing with languages you're less familiar with. The haskell portion was really interesting and definitely shows that you did your research.

Unfortunately nothing really comes to mind right away in terms of deeper analysis of go - most of my work has been focused on a few specific network-related problems so I'm a little more familiar with that aspect. Anyway, it seems like details on the benchmarking tool are in the reddit thread (I didn't see that you commented further down in there) so you've already got a better understanding of that.

Anyway, I don't think you've put too many people off. It was still a well-written article with quite a bit of in depth analysis. I'm looking forward to the next one. :)
